"""empty message

Revision ID: 05c0ac028c5b
Revises: 1f2d4d83e68f
Create Date: 2024-10-29 12:28:13.738132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05c0ac028c5b'
down_revision = '1f2d4d83e68f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diary', schema=None) as batch_op:
        batch_op.alter_column('datetime',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text("('')"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diary', schema=None) as batch_op:
        batch_op.alter_column('datetime',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text("('')"))

    # ### end Alembic commands ###
