"""empty message

Revision ID: 0a86efe647b7
Revises: d14775a895f3
Create Date: 2024-10-29 15:10:42.491091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a86efe647b7'
down_revision = 'd14775a895f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_date', sa.DateTime(), server_default='', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diary', schema=None) as batch_op:
        batch_op.drop_column('create_date')

    # ### end Alembic commands ###
