"""empty message

Revision ID: 1f2d4d83e68f
Revises: 392ae7f0bfea
Create Date: 2024-10-28 23:44:12.563859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f2d4d83e68f'
down_revision = '392ae7f0bfea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('datetime', sa.DateTime(), server_default='', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diary', schema=None) as batch_op:
        batch_op.drop_column('datetime')

    # ### end Alembic commands ###
