"""empty message

Revision ID: 2ab717f1bac2
Revises: 7bcb5c68aad3
Create Date: 2024-10-30 19:36:25.504952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ab717f1bac2'
down_revision = '7bcb5c68aad3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friday', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=1), nullable=True))
        batch_op.drop_column('todo')

    with op.batch_alter_table('monday', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=1), nullable=True))
        batch_op.drop_column('todo')

    with op.batch_alter_table('thursday', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=1), nullable=True))
        batch_op.drop_column('todo')

    with op.batch_alter_table('tuesday', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=1), nullable=True))
        batch_op.drop_column('todo')

    with op.batch_alter_table('wednesday', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=1), nullable=True))
        batch_op.drop_column('todo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wednesday', schema=None) as batch_op:
        batch_op.add_column(sa.Column('todo', sa.VARCHAR(length=10), server_default=sa.text("('')"), nullable=True))
        batch_op.drop_column('status')

    with op.batch_alter_table('tuesday', schema=None) as batch_op:
        batch_op.add_column(sa.Column('todo', sa.VARCHAR(length=10), server_default=sa.text("('')"), nullable=True))
        batch_op.drop_column('status')

    with op.batch_alter_table('thursday', schema=None) as batch_op:
        batch_op.add_column(sa.Column('todo', sa.VARCHAR(length=10), server_default=sa.text("('')"), nullable=True))
        batch_op.drop_column('status')

    with op.batch_alter_table('monday', schema=None) as batch_op:
        batch_op.add_column(sa.Column('todo', sa.VARCHAR(length=10), server_default=sa.text("('')"), nullable=True))
        batch_op.drop_column('status')

    with op.batch_alter_table('friday', schema=None) as batch_op:
        batch_op.add_column(sa.Column('todo', sa.VARCHAR(length=10), server_default=sa.text("('')"), nullable=True))
        batch_op.drop_column('status')

    # ### end Alembic commands ###
