"""empty message

Revision ID: 392ae7f0bfea
Revises: 684deb18756c
Create Date: 2024-10-28 23:43:23.097085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '392ae7f0bfea'
down_revision = '684deb18756c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('datetime', sa.DateTime(), server_default='', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diary', schema=None) as batch_op:
        batch_op.drop_column('datetime')

    # ### end Alembic commands ###
