"""empty message

Revision ID: 49166575ec10
Revises: 6c944dfc2821
Create Date: 2024-10-28 19:52:54.480916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49166575ec10'
down_revision = '6c944dfc2821'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('todo', sa.String(length=10), server_default='X', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diary', schema=None) as batch_op:
        batch_op.drop_column('todo')

    # ### end Alembic commands ###
