"""empty message

Revision ID: 4c2403a46276
Revises: 05c0ac028c5b
Create Date: 2024-10-29 12:36:58.503525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c2403a46276'
down_revision = '05c0ac028c5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_diary')
    with op.batch_alter_table('diary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_date', sa.DateTime(), server_default='', nullable=True))
        batch_op.drop_column('datetime')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('datetime', sa.DATETIME(), server_default=sa.text("('')"), nullable=True))
        batch_op.drop_column('create_date')

    op.create_table('_alembic_tmp_diary',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('emotion', sa.VARCHAR(length=10), nullable=False),
    sa.Column('distract', sa.VARCHAR(length=10), nullable=False),
    sa.Column('todo', sa.VARCHAR(length=10), server_default=sa.text("'X'"), nullable=False),
    sa.Column('datetime', sa.DATETIME(), server_default=sa.text("('')"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
