"""empty message

Revision ID: 560ddcab613f
Revises: 37fa1afccd42
Create Date: 2024-10-28 15:38:03.798872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '560ddcab613f'
down_revision = '37fa1afccd42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), nullable=False))

    # ### end Alembic commands ###
