"""empty message

Revision ID: 62fac6b1c5e7
Revises: 0a86efe647b7
Create Date: 2024-10-29 15:26:05.382309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62fac6b1c5e7'
down_revision = '0a86efe647b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diary', schema=None) as batch_op:
        batch_op.drop_column('create_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_date', sa.DATETIME(), server_default=sa.text("('')"), nullable=True))

    # ### end Alembic commands ###
