"""empty message

Revision ID: 66de5ecc107f
Revises: 2ab717f1bac2
Create Date: 2024-10-30 22:32:12.795044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66de5ecc107f'
down_revision = '2ab717f1bac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mainpage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mainpage')
    # ### end Alembic commands ###
