"""empty message

Revision ID: 6c944dfc2821
Revises: 560ddcab613f
Create Date: 2024-10-28 19:40:44.170106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c944dfc2821'
down_revision = '560ddcab613f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('todo', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diary', schema=None) as batch_op:
        batch_op.drop_column('todo')

    # ### end Alembic commands ###
