"""empty message

Revision ID: 7bcb5c68aad3
Revises: cbf50d6829bf
Create Date: 2024-10-30 17:02:41.310821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bcb5c68aad3'
down_revision = 'cbf50d6829bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friday', schema=None) as batch_op:
        batch_op.add_column(sa.Column('todo', sa.String(length=10), server_default='', nullable=True))

    with op.batch_alter_table('monday', schema=None) as batch_op:
        batch_op.add_column(sa.Column('todo', sa.String(length=10), server_default='', nullable=True))

    with op.batch_alter_table('thursday', schema=None) as batch_op:
        batch_op.add_column(sa.Column('todo', sa.String(length=10), server_default='', nullable=True))

    with op.batch_alter_table('tuesday', schema=None) as batch_op:
        batch_op.add_column(sa.Column('todo', sa.String(length=10), server_default='', nullable=True))

    with op.batch_alter_table('wednesday', schema=None) as batch_op:
        batch_op.add_column(sa.Column('todo', sa.String(length=10), server_default='', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wednesday', schema=None) as batch_op:
        batch_op.drop_column('todo')

    with op.batch_alter_table('tuesday', schema=None) as batch_op:
        batch_op.drop_column('todo')

    with op.batch_alter_table('thursday', schema=None) as batch_op:
        batch_op.drop_column('todo')

    with op.batch_alter_table('monday', schema=None) as batch_op:
        batch_op.drop_column('todo')

    with op.batch_alter_table('friday', schema=None) as batch_op:
        batch_op.drop_column('todo')

    # ### end Alembic commands ###
