"""empty message

Revision ID: b1d96900e764
Revises: 62fac6b1c5e7
Create Date: 2024-10-30 16:10:03.691765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1d96900e764'
down_revision = '62fac6b1c5e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friday', schema=None) as batch_op:
        batch_op.add_column(sa.Column('highlight', sa.String(length=10), server_default='', nullable=True))

    with op.batch_alter_table('monday', schema=None) as batch_op:
        batch_op.add_column(sa.Column('highlight', sa.String(length=10), server_default='', nullable=True))

    with op.batch_alter_table('thursday', schema=None) as batch_op:
        batch_op.add_column(sa.Column('highlight', sa.String(length=10), server_default='', nullable=True))

    with op.batch_alter_table('tuesday', schema=None) as batch_op:
        batch_op.add_column(sa.Column('highlight', sa.String(length=10), server_default='', nullable=True))

    with op.batch_alter_table('wednesday', schema=None) as batch_op:
        batch_op.add_column(sa.Column('highlight', sa.String(length=10), server_default='', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wednesday', schema=None) as batch_op:
        batch_op.drop_column('highlight')

    with op.batch_alter_table('tuesday', schema=None) as batch_op:
        batch_op.drop_column('highlight')

    with op.batch_alter_table('thursday', schema=None) as batch_op:
        batch_op.drop_column('highlight')

    with op.batch_alter_table('monday', schema=None) as batch_op:
        batch_op.drop_column('highlight')

    with op.batch_alter_table('friday', schema=None) as batch_op:
        batch_op.drop_column('highlight')

    # ### end Alembic commands ###
