"""empty message

Revision ID: cbf50d6829bf
Revises: b1d96900e764
Create Date: 2024-10-30 16:30:01.102208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbf50d6829bf'
down_revision = 'b1d96900e764'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('highlight',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('friday', schema=None) as batch_op:
        batch_op.alter_column('highlight',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("('')"))

    with op.batch_alter_table('monday', schema=None) as batch_op:
        batch_op.alter_column('highlight',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("('')"))

    with op.batch_alter_table('thursday', schema=None) as batch_op:
        batch_op.alter_column('highlight',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("('')"))

    with op.batch_alter_table('tuesday', schema=None) as batch_op:
        batch_op.alter_column('highlight',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("('')"))

    with op.batch_alter_table('wednesday', schema=None) as batch_op:
        batch_op.alter_column('highlight',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("('')"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wednesday', schema=None) as batch_op:
        batch_op.alter_column('highlight',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("('')"))

    with op.batch_alter_table('tuesday', schema=None) as batch_op:
        batch_op.alter_column('highlight',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("('')"))

    with op.batch_alter_table('thursday', schema=None) as batch_op:
        batch_op.alter_column('highlight',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("('')"))

    with op.batch_alter_table('monday', schema=None) as batch_op:
        batch_op.alter_column('highlight',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("('')"))

    with op.batch_alter_table('friday', schema=None) as batch_op:
        batch_op.alter_column('highlight',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("('')"))

    op.drop_table('highlight')
    # ### end Alembic commands ###
