"""empty message

Revision ID: d14775a895f3
Revises: 492c6c2ef874
Create Date: 2024-10-29 13:28:20.904559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd14775a895f3'
down_revision = '492c6c2ef874'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diary', schema=None) as batch_op:
        batch_op.drop_column('create_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_date', sa.DATETIME(), server_default=sa.text("('')"), nullable=False))

    # ### end Alembic commands ###
